#import serializers
from .usuarioSerializer import UsuarioSerializer
from .ProductoSerializer import ProductoSerializer
from .cocinaSerializer import CocinaSerializer
from .limpiezaSerializer import LimpiezaSerializer
from .proveedorSerializer import ProveedorSerializer